# Generated by Django 3.1.1 on 2020-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurseryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
